inherit_from: .rubocop_todo.yml
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Style/StringConcatenation:
  Exclude:
    - 'app/helpers/application_helper.rb'
Layout/LineLength:
  Max: 166
Metrics/AbcSize:
  Max: 41
Metrics/BlockLength:
  Max: 110